<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXPhGifi\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXPhGifi/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXPhGifi.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXPhGifi\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXPhGifi\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XPhGifi',
    'container.build_id' => '254c04b0',
    'container.build_time' => 1528135609,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXPhGifi');
